# permissions to do edit policyfunctions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policyfunction-editor-role
rules:
- apiGroups:
  - rapid.k8s.starkandwayne.com
  resources:
  - policyfunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rapid.k8s.starkandwayne.com
  resources:
  - policyfunctions/status
  verbs:
  - get
  - patch
  - update
