# permissions to do viewer policyfunctions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policyfunction-viewer-role
rules:
- apiGroups:
  - rapid.k8s.starkandwayne.com
  resources:
  - policyfunctions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rapid.k8s.starkandwayne.com
  resources:
  - policyfunctions/status
  verbs:
  - get
