
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rapid.k8s.starkandwayne.com
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rapid.k8s.starkandwayne.com
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rapid.k8s.starkandwayne.com
  resources:
  - policyfunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rapid.k8s.starkandwayne.com
  resources:
  - policyfunctions/status
  verbs:
  - get
  - patch
  - update
