apiVersion: v1
kind: Namespace
metadata:
  name: test-ruby-add-annotations
  labels:
    ruby-add-annotations: "true"
---
apiVersion: rapid.k8s.starkandwayne.com/v1beta1
kind: Policy
metadata:
  name: ruby-add-annotations
spec:
  policyfunction:
    name: ruby-add-annotations
    params:
      message: "The ruby-always-fails policy has spoken. That's a no for you."
  webhooktemplate:
    rules:
      - apiGroups: [""]
        apiVersions: ["*"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions: [{key: "ruby-add-annotations", operator: In, values: ["true"]}]
    failurePolicy: Fail
