apiVersion: rapid.k8s.starkandwayne.com/v1beta1
kind: PolicyFunctionTemplate
metadata:
  name: policyfunctiontemplate-ruby-always-fail
spec:
  language: ruby
  language_webhook_service: tiny-kubernetes-webhooks-webhook-service-languages
  handler_script: |-
    # admission_review - https://godoc.org/k8s.io/api/admission/v1beta1#AdmissionRequest
    # admission_resp - https://godoc.org/k8s.io/api/admission/v1beta1#AdmissionResponse
    def handler(admission_review, params, cache_dir)
      admission_resp = {}
      admission_resp[:allowed] = false
      admission_resp[:status] = {
        message: params[:message]
      }
      admission_resp
    end
  params:
  - name: message
    type: string
    description: Error message to show for all the failures
